name: Run PHPUnit Tests

on:
  push:
    branches:
      branches: [ "main","nested-feature", "mazed-dev" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

       name: Run PHPUnit
        run: |
          composer test:unit
          TEST_EXIT_CODE=$?
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "PHPUnit tests failed. Aborting commit."
            exit $TEST_EXIT_CODE
          fi